version: "3"
services:
  filebrowser:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    volumes:
      - ${BASE_DIR}/config/filebrowser.json:/.filebrowser.json
      - ${BASE_DIR}/config/database.db:/database.db
      - ${FILE_DIR}:/srv
    user: "${UID}:${GID}"
    ports:
      - 5000:80
    networks:
      apm_net:
        ipv4_address: ${IP_RAAGE}.11

networks:
    apm_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${IP_RAAGE}.0/16
